/*
 *    uhInfo
 *    Copyright (C) 2022
 */

#ifndef _UHILOGO_H_
#define _UHILOGO_H_

/* XPM */
static const char *uhilogo[] = {
/* columns rows colors chars-per-pixel */
"70 70 140 2 ","   c None",".  c #333784","X  c #353985","o  c #393C85","O  c #363A8B","+  c #3A3D8B","@  c #373B91","#  c #393D95","$  c #3A3F99",
"%  c #3D4084","&  c #3E4194","*  c #3C419D","=  c #3E43A3","-  c #3F44A8",";  c #424485",":  c #464886",">  c #42458B",",  c #464888","<  c #4A4C8B",
"1  c #57588E","2  c #424492","3  c #494A94","4  c #44469D","5  c #4E4F98","6  c #515295","7  c #52529C","8  c #4045A5","9  c #4549A3","0  c #494BA2",
"q  c #4146AC","w  c #4448AC","e  c #4A4EAB","r  c #5555A2","t  c #4147B0","y  c #4449B3","u  c #494EB4","i  c #454CBD","p  c #494EBB","a  c #4C50BC",
"s  c #5455B4","d  c #5355BB","f  c #5F62AB","g  c #6969A0","h  c #6B6AB3","j  c #6262BB","k  c #7875B5","l  c #7C79B2","z  c #7775BD","x  c #474EC2",
"c  c #484FC5","v  c #484FC8","b  c #4C52C4","n  c #4950CB","m  c #5155C5","M  c #5658C4","N  c #5156CB","B  c #5559CC","V  c #5B5DCD","C  c #4D54D4",
"Z  c #4E56DA","A  c #5056D2","S  c #555AD4","D  c #5B5ED4","F  c #5057DA","G  c #535ADC","H  c #595EDC","J  c #5D60DB","K  c #6162C5","L  c #6968C2",
"P  c #6263CC","I  c #6365D1","U  c #6A6BD6","Y  c #6566D9","T  c #686ADF","R  c #535BE3","E  c #595FE6","W  c #545DEA","Q  c #585FE9","!  c #565FF1",
"~  c #555FF2","^  c #565FF0","/  c #5962E5","(  c #5C61E5",")  c #5F63E4","_  c #5D62E6","`  c #5D63E1","'  c #5960EA","]  c #5C62EA","[  c #5860ED",
"{  c #5B62EC","}  c #5B62EE","|  c #5D63EC"," . c #5E63EC",".. c #5D63EC","X. c #5760F2","o. c #5760F3","O. c #5761F5","+. c #5760F2","@. c #5961F0",
"#. c #5861F2","$. c #5961F3","%. c #5A62F3","&. c #5D63F1","*. c #5F65F2","=. c #5861F4","-. c #5961F4",";. c #5861F5",":. c #5A63F5",">. c #5862F7",
",. c #5B63F6","<. c #5C64F7","1. c #5F66F7","2. c #5A62F5","3. c #5762F8","4. c #5862F8","5. c #5A65F9","6. c #5B65FD","7. c #6366E4","8. c #6669E6",
"9. c #686BE6","0. c #6065EE","q. c #6066F5","w. c #6368F3","e. c #666AF1","r. c #666AF0","t. c #6C6FF0","y. c #6169FF","u. c #626BFF","i. c #6870FF",
"p. c #6C72FF","a. c #6C71FE","s. c #7174F7","d. c #7D80FF","f. c #7F84FF","g. c #8482D9","h. c #9491D0","j. c #8284FF","k. c #8289FF","l. c #8D8DFF",
"z. c #9B99FF",
/* pixels */
"                                                                                                                                             ",
"                                                                                                                                             ",
"                                                                    t.<.$.>.>.>.                                                             ",
"                                                                  _ R n i y x n G W                                                          ",
"                                                                P Z i $ o ; o = n C                                                          ",
"                                                                m n -           a n i                                                        ",
"                                                                a n n           A n q                                                        ",
"                                                                7 p C W 6.y.q.Q n y                                                          ",
"                                                                  & y c n Z C x - >                                                          ",
"                                                                    j n v # O .                                                              ",
"                                                                    B n x e                                         n n n                    ",
"                                                                  B N n y                                           n n n                    ",
"            j.                                                  B A n i 4                                         n n n n                    ",
"        q.>.X.X.>.6.                                        I D F n i =                                           n n n n                    ",
"      | W C v n Z R W                                   U S F C n i =                                             n n n n                    ",
"    J R n - @ $ y C G /                             J E H F n c y *                                               n n n n                    ",
"    H n y X     & x C C                     9._ E R G C n n i 8 #                                                 n n n n                    ",
"  K N n -       5 p n n         s.w.*.&.{ ' R R Z C n n i w *                                                     n n n n                    ",
"  d n n y         b n n <.4.>.$.{ W R R Z Z C n v x y q * >                                                       n n n n                    ",
"  s n n c         N n i G Z F Z C C C v c c i y q = O <                                                           n n n n                    ",
"  r a n C       Y F n q v v c x x i i y t - $ O o                                                                 n v n n                    ",
"    y n Z ~   d.{ C i * y q q 8 = * @ O X <                           n n                                         n n n n                    ",
"    2 y n R >.$.G c - X . . X X 1                                   n n n                                         n n n n                    ",
"      # q x n n i = X                                               n n n                                         n n n n                    ",
"        + O * $ . %                                                 n n n                                         n   n n                    ",
"                                                                    n n n                                             n n                    ",
"                                                                    n n n                                             n n                    ",
"                                                                    n n n                 n n                   n   n n n                    ",
"                                                                    n n n n             n n n                   n   v n n                    ",
"                                                                    n v n n           n n n n n               n n n n n n                    ",
"                                                                    n n n n         n n v n n n             n n n n n n n                    ",
"                                                                    n n n n         n n n n n n             n n   n n n n n                  ",
"                                                                      n n n       n n n   n n n v         n n n   l n n v n                  ",
"                                                                      n n n       n n n   n n n n       n n n       n n n n                  ",
"                                                                        n n     n n n       n n n     n n n n       n n n                    ",
"                                                n                   n   n n     n n n       n n n n n n n n         n n n                    ",
"                                              n n                   n   n n     n n         n n n n n n n                                    ",
"                                              n n                 n n   n n   n n n           n n n n n                                      ",
"                                              n n                 n n v n n   n n             n v C                                          ",
"                                            n n n               n n n n n n   n n                                                            ",
"                                            n n n               n n   n n n n n n                                                            ",
"                                            n n n n           n n n   n n n n n                                                              ",
"                            n               n n n n         n n n     n n v n n                                                 a.i.         ",
"                          n n n             n n n n         n n       n n n n n                                             q.>.W W X.O.     ",
"                          n n n           n n n n n n     n n n       n n n n                                             _ R n i i n Z W    ",
"                        n v n n           n n   n n n v n n n         n n n n                                           I F n = . X = c C C  ",
"                          n n n           n n   n n n n n n           n n v n                                   k.w.0. .] i i o     3 i C v  ",
"                          n n n           n n   v n n n n             n n n n                         l.8.) J H D S A N i x i         b n x  ",
"                          n n n         n n n     n n n                 n n                     T J D B N m b p p p y w w i n /       A n y  ",
"                          n n n         n n                                             z.U V B m m a u u t q 8 8 $ $ # + x C W y.a.{ Z i *  ",
"                          n n n       n n n                                         U V M m p u y q 8 = $ + O O X X o o ; - i Z W W Z x =    ",
"                          n n v       n n                                     g.P M a p u 8 = = $ O O . . . ;             g & q i i t $ ,    ",
"                          n n n     n n n                                   K d s y w 8 * $ O X . X                           o X . X        ",
"                          n n n   n n n                                 L d u w 8 = $ + X X                                                  ",
"                          n n n n n n n                             h.s e w = * $ O .                                                        ",
"                          n C v n n n                             z e w = * $ O X                                                            ",
"                          n n n n n                             h e 8 = $ @ X                                                                ",
"                            n n n                             k 9 8 * $ +                                                                    ",
"                                                              0 e.<.>.$.O.3.                                                                 ",
"                                                            r 7.Q C c c C R W                                                                ",
"                                                            4 H n y O O = c Z C                                                              ",
"                                                            B A i O     2 i C n                                                              ",
"                                                            M n x f       b n n                                                              ",
"                                                            a n n S       N n y                                                              ",
"                                                            0 x C R k.   .F c =                                                              ",
"                                                              9 c Z ! >.R n q >                                                              ",
"                                                              6 * y c c i = X                                                                ",
"                                                                  X O O . :                                                                  ",
"                                                                                                                                             ",
"                                                                                                                                             "};

#endif // _UHILOGO_H_
